import pytest
from app.data_processor import validate_email, calculate_average, process_user_data

def test_valid_email():
    assert validate_email("test@example.com") == True

def test_invalid_email():
    assert validate_email("invalid-email") == False

def test_average():
    assert calculate_average([10, 20, 30]) == 20.0

# More tests will be generated by AI during the workshop

def test_average_empty_list():
    with pytest.raises(ZeroDivisionError):
        calculate_average([])  # This should crash – but we expect it!

def test_invalid_email_advanced():
    assert validate_email("user@com") == False  # Should fail currently (your code wrongly returns True)
